import Link from "next/link";
import { notFound } from "next/navigation";
import { Card } from "@/components/ui/Card";
import { TeacherAgileGameControls } from "@/components/agile/TeacherAgileGameControls";
import { AgileLiveRefresh } from "@/components/agile/AgileLiveRefresh";
import { getAgileGameTemplate } from "@/lib/agileGames/catalog";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";

export default async function TeacherAgileGameDetail({params}:{params:Promise<{gameId:string}>}){const teacher=await requireRole("teacher");const {gameId}=await params;const supabase=await createClient();const {data:game}=await supabase.from("agile_game_sessions").select("id,title,template_id,status").eq("id",gameId).eq("teacher_id",teacher.id).maybeSingle<{id:string;title:string;template_id:string;status:string}>();if(!game)notFound();const [{data:teams},{data:players}]=await Promise.all([supabase.from("agile_game_teams").select("id,name,color").eq("session_id",gameId),supabase.from("agile_game_players").select("student_id,team_id,roles,profiles!agile_game_players_student_id_fkey(display_name)").eq("session_id",gameId)]);const template=getAgileGameTemplate(game.template_id);return <main className="space-y-6"><AgileLiveRefresh active={game.status!=="finished"}/><section className="rounded-[2rem] bg-slate-950 p-7 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-wide text-amber-300">{game.status==="lobby"?"Lobby — zapisy do zespołów":game.status==="active"?"Sprint aktywny":"Gra zakończona"}</p><h1 className="mt-2 text-4xl font-black">{template?.emoji} {game.title}</h1><p className="mt-3 text-slate-300">{template?.mission}</p></div><div className="flex flex-wrap gap-3"><TeacherAgileGameControls sessionId={game.id} canStart={game.status==="lobby"}/>{game.template_id==="zoo-sprint"?<Link href={`/nauczyciel/gry-agile/zoo?sessionId=${game.id}`} className="rounded-xl bg-amber-300 px-5 py-3 font-black text-slate-950">Otwórz planszę Zoo</Link>:null}</div></div></section><div className="grid gap-4 lg:grid-cols-2">{(teams??[]).map(team=>{const members=(players??[]).filter(player=>player.team_id===team.id);return <Card key={team.id} className="border-t-4" style={{borderTopColor:team.color}}><h2 className="text-xl font-black">{team.name} · {members.length} osób</h2><div className="mt-3 space-y-2">{members.map(member=><div key={member.student_id} className="rounded-xl bg-slate-50 p-3 text-sm"><strong>{(member.profiles as {display_name?:string}|null)?.display_name??"Uczeń"}</strong><span className="ml-2 text-slate-600">{(member.roles??[]).join(" · ")||"role po starcie"}</span></div>)}</div></Card>})}</div><Link href="/nauczyciel/gry-agile" className="inline-flex rounded-xl border border-slate-300 px-4 py-3 font-black">← Wszystkie gry</Link></main>}
