import Link from "next/link";
import { Card } from "@/components/ui/Card";
import { createAgileGameAction } from "@/lib/actions/agileGames";
import { AGILE_GAME_TEMPLATES } from "@/lib/agileGames/catalog";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";

export default async function TeacherClassGamesPage({searchParams}:{searchParams?:Promise<{classId?:string}>}) {
  const teacher=await requireRole("teacher");const selectedClassId=(await searchParams)?.classId;const supabase=await createClient();
  const [{data:classes},{data:games}]=await Promise.all([
    supabase.from("teacher_classes").select("id,name,group_name,school_grade").eq("teacher_id",teacher.id).order("school_grade"),
    supabase.from("agile_game_sessions").select("id,title,status,sprint_number,created_at,teacher_classes(name,group_name)").eq("teacher_id",teacher.id).order("created_at",{ascending:false}).limit(12),
  ]);
  return <main className="space-y-6">
    <section className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-indigo-700 via-violet-600 to-fuchsia-600 p-7 text-white shadow-xl sm:p-9"><p className="text-sm font-black uppercase tracking-[.16em] text-fuchsia-100">Gry klasowe</p><h1 className="mt-2 text-4xl font-black">Uruchom grę dla swojej klasy</h1><p className="mt-3 max-w-3xl text-indigo-100">Wybierz klasę i scenariusz. System otworzy lobby, wyśle uczniom zaproszenie i pozwoli im wybrać drużyny przed rozpoczęciem rozgrywki.</p></section>
    <Card><h2 className="text-2xl font-black text-slate-950">Nowa gra</h2><p className="mt-1 text-slate-600">Najpierw wybierz klasę, następnie rodzaj gry.</p><form action={createAgileGameAction} className="mt-5 grid gap-5"><select name="classId" defaultValue={selectedClassId??""} required className="rounded-xl border border-slate-300 bg-white px-4 py-3 font-bold text-slate-950"><option value="">Wybierz klasę</option>{(classes??[]).map(item=><option key={item.id} value={item.id}>Klasa {item.school_grade} · {item.name} / {item.group_name}</option>)}</select><div className="grid gap-4 sm:grid-cols-2">{AGILE_GAME_TEMPLATES.map(template=><label key={template.id} className="group cursor-pointer overflow-hidden rounded-2xl border-2 border-slate-200 bg-slate-50 p-5 transition hover:-translate-y-1 hover:border-violet-400 hover:shadow-lg"><input type="radio" name="templateId" value={template.id} required className="mr-3 size-4"/><span className="text-3xl">{template.emoji}</span><strong className="ml-3 text-xl text-slate-950">{template.title}</strong><span className="mt-3 block text-sm leading-relaxed text-slate-600">{template.description}</span><span className="mt-3 block text-sm font-black text-violet-700">Wybierz tę grę</span></label>)}</div><button type="submit" disabled={!classes?.length} className="min-h-14 rounded-xl bg-violet-600 px-6 font-black text-white shadow-lg transition hover:bg-violet-700 disabled:bg-slate-300">Utwórz lobby i zaproś klasę →</button></form>{!classes?.length?<p className="mt-3 text-sm font-bold text-amber-800">Najpierw utwórz klasę, aby uruchomić grę.</p>:null}</Card>
    <section><h2 className="text-2xl font-black text-slate-950">Ostatnie gry</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{(games??[]).map(game=><Link key={game.id} href={`/nauczyciel/gry-agile/${game.id}`} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-violet-400 hover:shadow-md"><p className="text-xs font-black uppercase text-violet-700">{game.status==="lobby"?"Lobby — oczekiwanie na uczniów":game.status==="active"?"Gra trwa":"Zakończona"}</p><h3 className="mt-1 text-xl font-black text-slate-950">{game.title}</h3><p className="mt-1 text-sm text-slate-600">Sprint {game.sprint_number}</p></Link>)}{!games?.length?<p className="text-slate-600">Nie uruchomiono jeszcze żadnej gry.</p>:null}</div></section>
  </main>;
}
