import Link from "next/link";
import { Card } from "@/components/ui/Card";
import { createAgileGameAction } from "@/lib/actions/agileGames";
import { AGILE_GAME_TEMPLATES } from "@/lib/agileGames/catalog";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";

export default async function TeacherAgileGamesPage() {
  const teacher = await requireRole("teacher");
  const supabase = await createClient();
  const [{ data: classes }, { data: games }] = await Promise.all([
    supabase.from("teacher_classes").select("id, name, group_name, school_grade").eq("teacher_id", teacher.id).order("school_grade"),
    supabase.from("agile_game_sessions").select("id, title, status, sprint_number, created_at, teacher_classes(name, group_name)").eq("teacher_id", teacher.id).order("created_at", { ascending: false }).limit(12),
  ]);
  return <main className="space-y-6"><section className="rounded-[2rem] bg-gradient-to-br from-amber-400 via-orange-500 to-rose-600 p-7 text-white sm:p-9"><p className="text-sm font-black uppercase tracking-[.16em] text-amber-100">Gry Agile</p><h1 className="mt-2 text-4xl font-black">Współpraca, sprinty i dobra zabawa</h1><p className="mt-3 max-w-3xl text-orange-50">Tworzysz grę dla klasy. Uczniowie sami wybierają zespół w lobby, a po starcie system rozdziela role — także wtedy, gdy zespół jest mały.</p></section><Card><h2 className="text-2xl font-black text-slate-950">Utwórz grę dla klasy</h2><form action={createAgileGameAction} className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,2fr)]"><select name="classId" required className="rounded-xl border border-slate-300 bg-white px-4 py-3 font-bold text-slate-950"><option value="">Wybierz klasę</option>{(classes ?? []).map((item) => <option key={item.id} value={item.id}>Klasa {item.school_grade} · {item.name} / {item.group_name}</option>)}</select><div className="grid gap-3 sm:grid-cols-2">{AGILE_GAME_TEMPLATES.map((template) => <label key={template.id} className="cursor-pointer rounded-2xl border border-slate-200 bg-slate-50 p-4 transition hover:border-orange-300 hover:bg-orange-50"><input type="radio" name="templateId" value={template.id} required className="mr-2" /><span className="text-2xl">{template.emoji}</span><strong className="ml-2 text-slate-950">{template.title}</strong><span className="mt-2 block text-sm text-slate-600">{template.description}</span></label>)}</div><button type="submit" disabled={!classes?.length} className="rounded-xl bg-orange-600 px-5 py-3 font-black text-white disabled:bg-slate-300 lg:col-span-2">Otwórz lobby gry</button></form>{!classes?.length ? <p className="mt-3 text-sm font-bold text-amber-800">Najpierw utwórz klasę, aby zaprosić ją do gry.</p> : null}</Card><section><h2 className="text-2xl font-black text-slate-950">Ostatnie gry</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{(games ?? []).map((game) => <Link key={game.id} href={`/nauczyciel/gry-agile/${game.id}`} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-orange-300"><p className="text-xs font-black uppercase text-orange-700">{game.status === "lobby" ? "Lobby — zapisy" : game.status === "active" ? "Sprint trwa" : "Zakończona"}</p><h3 className="mt-1 text-xl font-black text-slate-950">{game.title}</h3><p className="mt-1 text-sm text-slate-600">Sprint {game.sprint_number}</p></Link>)}{!games?.length ? <p className="text-slate-600">Nie utworzono jeszcze gry.</p> : null}</div></section></main>;
}
