export type ZooTask = { id:number; role:string; title:string; cost:number; visitors:number; budgetImpact:number; outcome:string; blocks?:number[]; crisis?:string };

const ROLE_TASKS = [
  ["Afrykarium", ["Awaryjnie nakarm lwy", "Wezwij lekarza do lwów", "Zmodernizuj wybieg lwów", "Kup system chłodzenia", "Zbuduj punkt obserwacyjny", "Wprowadź wzbogacenie behawioralne", "Napraw ogrodzenie słoni", "Ulecz chorego pawiana", "Uzupełnij zapas leków", "Zatrudnij dodatkowego opiekuna", "Otwórz wybieg sawanny", "Kup roczny pakiet żywności dla lwów", "Zorganizuj pokaz opiekunów", "Zbuduj strefę cienia", "Odnowić kwarantannę"]],
  ["Akwarium", ["Zakleić szybę szarą taśmą", "Fachowo wymienić szybę", "Uzupełnić wodę", "Naprawić filtr", "Zbadać chore ryby", "Kupić pompę awaryjną", "Oczyścić zbiornik rekinów", "Wymienić oświetlenie", "Zbudować tunel dla gości", "Kupić nowe koralowce", "Zabezpieczyć instalację", "Zatrudnić akwarystę", "Naprawić system tlenu", "Otworzyć nocne zwiedzanie", "Zmodernizować laboratorium wody"]],
  ["Ptaszarnia", ["Naprawić odpływy", "Nowa trasa dla rodzin", "Wyleczyć papugi", "Naprawić dach ptaszarni", "Kupić siatkę zabezpieczającą", "Zbudować wyspę flamingów", "Ogrzać wybieg zimowy", "Odtworzyć miejsca lęgowe", "Kupić inkubator", "Zatrudnić ornitologa", "Zabezpieczyć karmę przed myszami", "Otworzyć pokaz lotów", "Wyciszyć strefę lęgową", "Zmodernizować wolierę", "Zbadać jakość powietrza"]],
  ["Insektarium i media", ["Kampania o ochronie zwierząt", "Tania atrakcja weekendowa", "Odpowiedzieć na kryzys w mediach", "Uruchomić sprzedaż online", "Naprawić stronę zoo", "Zbudować hotel dla owadów", "Kupić rzadkie motyle", "Przygotować materiały szkolne", "Zaprosić lokalne media", "Zorganizować dzień rodzinny", "Wprowadzić mapę mobilną", "Zatrudnić rzecznika", "Odnowić identyfikację zoo", "Zorganizować zbiórkę funduszy", "Przeprowadzić badanie gości"]],
] as const;

export const ZOO_TASKS: ZooTask[] = ROLE_TASKS.flatMap(([role,titles],roleIndex)=>titles.map((title,index)=>{const id=(roleIndex+1)*100+index+1;const visitors=[-3,5,9,2,4,7,1][(index*2+roleIndex)%7];const cost=[5,9,13,7,11,6,12][(index+roleIndex)%7];const task:ZooTask={id,role,title,cost,visitors,budgetImpact:0,outcome:visitors<0?`${title} było rozwiązaniem szybkim, ale obniżyło jakość doświadczenia gości. Zoo straciło część zainteresowania.`:`${title} rozwiązało problem w sposób zauważalny dla gości. Lepsze warunki i opinie zwiększyły zainteresowanie zoo.`};if(id===101){task.budgetImpact=-1;task.outcome="Awaryjne dokarmienie lwów ochroniło zwierzęta i uspokoiło gości, ale droższa karma będzie stale obciążać budżet."}if(id===104){task.title="Ogranicz dofinansowanie Afrykarium";task.cost=0;task.visitors=-9;task.budgetImpact=3;task.outcome="Oszczędność zwiększyła budżet, ale gorsze warunki Afrykarium wyraźnie obniżyły zaufanie gości."}if(id===204){task.budgetImpact=1;task.outcome="Naprawa filtra poprawiła jakość wody i zatrzymała kosztowne straty w instalacji."}if(id===201){task.cost=4;task.visitors=-3;task.budgetImpact=1;task.outcome="Taśma zatrzymała wyciek tylko na chwilę. Widoczna prowizorka pogorszyła opinie gości, ale odsunęła koszt fachowej naprawy.";task.blocks=[202]}if(id===202){task.cost=12;task.visitors=5;task.budgetImpact=1;task.outcome="Fachowa wymiana szyby usunęła przyczynę wycieku. Zoo nie musi już stale dolewać wody, a bezpieczne akwarium odzyskało zaufanie gości.";task.blocks=[201]}return task;}));
export const ZOO_TASK_BY_ID = new Map(ZOO_TASKS.map(task=>[task.id,task]));
export const ZOO_ROLES = ROLE_TASKS.map(([role])=>role);

export type ZooInitialProblem = { id:string; taskIds:number[]; failure:string };
export const ZOO_INITIAL_PROBLEMS: ZooInitialProblem[] = [
  {id:"lion-food",taskIds:[112],failure:"Nie kupiono zapasów żywności dla lwów. Awaryjne karmienie i skargi gości ograniczyły środki w kolejnym sprincie."},
  {id:"aquarium-leak",taskIds:[201,202],failure:"Nienaprawiony wyciek wymusił ciągłe dolewanie wody i kosztowne dostawy awaryjne."},
  {id:"aviary-roof",taskIds:[304,305],failure:"Dziurawa woliera nie została zabezpieczona. Ptaszarnię trzeba było częściowo zamknąć."},
  {id:"sick-baboon",taskIds:[108],failure:"Chory pawian nie otrzymał pomocy. Stan zwierzęcia pogorszył się, a goście zgłaszali zastrzeżenia."},
];

export type ZooEvent = { id:string; title:string; body:string; requiredTaskIds:number[]; penaltyVisitors:number; penaltyBudget:number; success:string; failure:string; isSetup?:boolean };
export const ZOO_EVENTS: ZooEvent[] = [
  {id:"zoo-after-mismanagement",title:"Zoo po złym zarządzaniu",body:"Nowy zespół przejmuje zoo w trudnej sytuacji: brakuje żywności dla lwów, akwarium przecieka, ptasia woliera jest dziurawa, a pawian wymaga leczenia. W tym sprincie ustalcie, co ratujecie najpierw.",requiredTaskIds:[],penaltyVisitors:0,penaltyBudget:0,success:"Zespół uporządkował najpilniejsze sprawy.",failure:"Nie wszystkie pilne sprawy zostały zabezpieczone.",isSetup:true},
  {id:"mice-food",title:"Myszy zjadły zapasy",body:"Magazyn karmy jest pusty. Bez zabezpieczenia karmy i uzupełnienia zapasów zwierzęta zaczną głodować.",requiredTaskIds:[112,311],penaltyVisitors:18,penaltyBudget:8,success:"Zapasy uratowane, zwierzęta są bezpieczne.",failure:"Zwierzęta głodują, a awaryjny zakup karmy zmniejsza kolejny budżet."},
  {id:"aquarium-leak",title:"Wyciek w akwarium",body:"Pęknięta szyba przepuszcza wodę. Możecie użyć taniej taśmy albo wykonać fachową naprawę.",requiredTaskIds:[201,202],penaltyVisitors:14,penaltyBudget:10,success:"Wyciek został zatrzymany, więc nie trzeba stale uzupełniać wody.",failure:"Przez nienaprawiony wyciek pracownicy musieli stale dolewać wodę. Awaryjne dostawy pochłonęły część punktów dostępnych w kolejnym sprincie."},
  {id:"weak-lions",title:"Lwy są osłabione",body:"Opiekun zgłasza brak apetytu i apatię lwów. Potrzebna jest żywność lub lekarz.",requiredTaskIds:[112,102],penaltyVisitors:22,penaltyBudget:12,success:"Lwy odzyskują siły.",failure:"Stan lwów gwałtownie się pogarsza i wybucha kryzys wizerunkowy."},
  {id:"aviary-roof",title:"Burza uszkodziła ptaszarnię",body:"Dach i odpływy nie wytrzymały ulewy. Ptaki wymagają szybkiego zabezpieczenia.",requiredTaskIds:[301,304,305],penaltyVisitors:12,penaltyBudget:7,success:"Ptaszarnia została zabezpieczona.",failure:"Kolejna ulewa zamyka ptaszarnię dla gości."},
  {id:"media-crisis",title:"Film z zaniedbanego wybiegu trafił do sieci",body:"Goście oczekują wyjaśnień i konkretnych działań, nie samej reklamy.",requiredTaskIds:[401,403,409,412],penaltyVisitors:20,penaltyBudget:4,success:"Zoo odzyskuje zaufanie opinii publicznej.",failure:"Negatywne publikacje obniżają frekwencję."},
  {id:"family-crowd",title:"Tłok podczas rodzinnego weekendu",body:"Ścieżki są zablokowane, a rodziny rezygnują ze zwiedzania.",requiredTaskIds:[302,410,411],penaltyVisitors:10,penaltyBudget:3,success:"Ruch gości został uporządkowany.",failure:"Kolejki i złe opinie odstraszają odwiedzających."},
  {id:"water-quality",title:"Zła jakość wody",body:"Czujniki pokazują spadek tlenu i problemy z filtrem.",requiredTaskIds:[204,206,213,215],penaltyVisitors:16,penaltyBudget:9,success:"Parametry wody wracają do normy.",failure:"Część zbiorników zostaje zamknięta, a leczenie ryb jest kosztowne."},
  {id:"medicine-shortage",title:"Brakuje leków",body:"Kwarantanna jest pełna, a magazyn weterynaryjny niemal pusty.",requiredTaskIds:[102,109,115],penaltyVisitors:13,penaltyBudget:8,success:"Zespół zabezpieczył leczenie zwierząt.",failure:"Choroby rozprzestrzeniają się na kolejne wybiegi."},
];
export const ZOO_EVENT_BY_ID = new Map(ZOO_EVENTS.map(event=>[event.id,event]));
