import Image from "next/image";
import { getEngineGame } from "@/lib/agileGames/engine";
import { getAgileGameTemplate } from "@/lib/agileGames/catalog";

type Team = { id:string; name:string; color:string; visitors:number; budget:number; crises:string[]; choices:number[] };
export function AgileFinalScreen({ templateId, teams }: { templateId:string; teams:Team[] }) {
  const engine=getEngineGame(templateId); const template=getAgileGameTemplate(templateId); const metric=engine?.metric??"odwiedzających"; const unit=engine?"pkt":"tys."; const sorted=[...teams].sort((a,b)=>b.visitors-a.visitors); const max=Math.max(1,...teams.map(team=>team.visitors));
  const feedback=(team:Team)=>{const missed=team.crises.length; if(!missed&&team.visitors>=170)return "Dobrze: zespół reagował na potrzeby i budował wartość małymi krokami. Skutek: rośnie zaufanie oraz wynik."; if(missed)return `Dobrze: wybrano ${team.choices.length} decyzji. Do poprawy: pominięto ${missed} kryzys(y). Skutek: konsekwencje obniżyły wynik i budżet.`; return "Dobrze: zespół konsekwentnie dostarczał elementy planu. Do poprawy: warto częściej sprawdzać potrzeby odbiorców.";};
  const theme={"zoo-sprint":"from-emerald-950 via-slate-950 to-amber-950","mars-mission":"from-orange-950 via-slate-950 to-violet-950","game-studio":"from-fuchsia-950 via-indigo-950 to-cyan-950","future-city":"from-emerald-950 via-cyan-950 to-slate-950"}[templateId]??"from-slate-950 to-slate-900";
  return <section className={`overflow-hidden rounded-[2rem] bg-gradient-to-br ${theme} text-white shadow-2xl`}><div className="relative min-h-60 overflow-hidden"><Image src={template?.finalImage??template?.image??"/agile-games/zoo-sprint.png"} alt={`Finał gry ${template?.title??"Agile"}`} fill className="object-cover opacity-65"/><div className="relative p-7 sm:p-10"><p className="text-sm font-black uppercase tracking-[.2em] text-amber-200">Finał · wspólna retrospektywa</p><h1 className="mt-2 text-4xl font-black">{template?.emoji} {template?.title}</h1><p className="mt-3 max-w-2xl text-lg text-white/90">Wasze decyzje stworzyły historię zespołów. Sprawdźcie wynik, skutki kryzysów i to, co warto zabrać do następnego sprintu.</p></div></div><div className="grid gap-6 p-6 lg:grid-cols-2"><div><h2 className="text-2xl font-black">Ranking i wykres: {metric}</h2><div className="mt-4 space-y-4">{sorted.map((team,index)=><div key={team.id}><div className="flex justify-between gap-3 text-sm font-black"><span>{index+1}. {team.name}</span><span>{team.visitors} {unit}</span></div><div className="mt-1 h-4 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full" style={{width:`${team.visitors/max*100}%`,background:team.color}}/></div></div>)}</div></div><div><h2 className="text-2xl font-black">Co przyniosły decyzje?</h2><div className="mt-4 space-y-3">{sorted.map(team=><article key={team.id} className="rounded-2xl bg-white/10 p-4" style={{borderLeft:`5px solid ${team.color}`}}><h3 className="font-black">{team.name}</h3><p className="mt-2 text-sm leading-relaxed text-slate-100">{feedback(team)}</p></article>)}</div></div></div><div className="border-t border-white/15 bg-slate-950/45 p-6"><h2 className="text-2xl font-black">Mapa decyzji: kryzys → skutek</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{sorted.flatMap(team=>team.crises.map((crisis,index)=><div key={`${team.id}-${index}`} className="rounded-2xl border border-rose-300/30 bg-rose-500/10 p-4"><b>{team.name}</b><p className="mt-1 text-sm text-rose-100">↳ {crisis}</p></div>))}{!sorted.some(team=>team.crises.length)?<p className="rounded-2xl bg-emerald-500/15 p-4 font-bold text-emerald-100">Żaden kryzys nie został pominięty — zespoły zabezpieczały potrzeby na czas.</p>:null}</div></div></section>;
}
