"use client";

import { useMemo, useState } from "react";
import { LessonTaskFrame } from "@/components/lessons/LessonTaskFrame";
import { LessonNumericKeypad } from "@/components/lessons/models/LessonNumericKeypad";

export const DECIMAL_EXPANSION_ACTIVITIES = ["decimal-expansion-example", "decimal-expansion-practice", "decimal-long-division", "decimal-period"] as const;
export type DecimalExpansionActivity = typeof DECIMAL_EXPANSION_ACTIVITIES[number];
export const isDecimalExpansionActivity = (value: string): value is DecimalExpansionActivity => DECIMAL_EXPANSION_ACTIVITIES.includes(value as DecimalExpansionActivity);

type Fraction = { n: number; d: number };
const FractionView = ({ value }: { value: Fraction }) => <span className="inline-grid min-w-10 grid-rows-2 text-center leading-none"><span className="border-b-2 border-current px-1 pb-1">{value.n}</span><span className="px-1 pt-1">{value.d}</span></span>;
const fractionLabel = (value: Fraction) => `${value.n} przez ${value.d}`;

const expansionTasks = [
  { f: { n: 3, d: 4 }, k: 25, result: "0,75" }, { f: { n: 7, d: 20 }, k: 5, result: "0,35" }, { f: { n: 9, d: 25 }, k: 4, result: "0,36" }, { f: { n: 11, d: 50 }, k: 2, result: "0,22" },
  { f: { n: 13, d: 40 }, k: 25, result: "0,325" }, { f: { n: 17, d: 125 }, k: 8, result: "0,136" }, { f: { n: 19, d: 200 }, k: 5, result: "0,095" }, { f: { n: 7, d: 8 }, k: 125, result: "0,875" },
] as const;
const divisionTasks = [
  { f: { n: 1, d: 3 }, result: "0,(3)", type: "okresowe" }, { f: { n: 5, d: 9 }, result: "0,(5)", type: "okresowe" }, { f: { n: 7, d: 6 }, result: "1,1(6)", type: "okresowe" },
  { f: { n: 2, d: 7 }, result: "0,(285714)", type: "okresowe" }, { f: { n: 4, d: 11 }, result: "0,(36)", type: "okresowe" }, { f: { n: 1, d: 6 }, result: "0,1(6)", type: "okresowe" },
] as const;
const periodTasks = [
  { f: { n: 3, d: 11 }, value: "0,(27)", type: "okresowe" }, { f: { n: 1, d: 8 }, value: "0,125", type: "skończone" }, { f: { n: 2, d: 3 }, value: "0,(6)", type: "okresowe" }, { f: { n: 7, d: 20 }, value: "0,35", type: "skończone" }, { f: { n: 5, d: 6 }, value: "0,8(3)", type: "okresowe" }, { f: { n: 1, d: 12 }, value: "0,08(3)", type: "okresowe" },
] as const;

type Props = { activity: DecimalExpansionActivity; seed: number; readOnly?: boolean; questionNumber?: number; questionCount?: number; onResultChange?: (correct: boolean | null, answerLabel?: string) => void };
const normalized = (value: string) => value.replace(/\s/gu, "").replace(".", ",");

export function DecimalExpansionL6Lab({ activity, readOnly = false, questionNumber = 1, questionCount = 1, onResultChange }: Props) {
  const index = Math.max(0, questionNumber - 1);
  const [answer, setAnswer] = useState(""); const [factor, setFactor] = useState(""); const [active, setActive] = useState<"factor" | "answer">("answer"); const [type, setType] = useState(""); const [feedback, setFeedback] = useState<"good" | "bad" | null>(null);
  const reset = () => { setFeedback(null); onResultChange?.(null); };
  const key = (value: string) => { const setter = active === "factor" ? setFactor : setAnswer; const current = active === "factor" ? factor : answer; if (value === "backspace") setter(current.slice(0, -1)); else if (value === "," && current.includes(",")) return; else setter(`${current}${value}`); reset(); };
  const periodToken = (token: "(" | ")") => { setActive("answer"); setAnswer((current) => `${current}${token}`); reset(); };
  const task: { f: Fraction; k?: number; result?: string; value?: string; type?: string } = useMemo(() => activity === "decimal-expansion-practice" ? expansionTasks[index % expansionTasks.length] : activity === "decimal-long-division" ? divisionTasks[index % divisionTasks.length] : periodTasks[index % periodTasks.length], [activity, index]);
  const confirm = () => { const correct = activity === "decimal-expansion-practice" ? Number(factor) === task.k && normalized(answer) === task.result : activity === "decimal-long-division" ? normalized(answer) === task.result : normalized(answer) === task.value && type === task.type; setFeedback(correct ? "good" : "bad"); onResultChange?.(correct, answer); };
  const field = (name: "factor" | "answer", label: string, width = "w-32") => <input aria-label={label} value={name === "factor" ? factor : answer} readOnly inputMode="none" onClick={() => setActive(name)} onFocus={() => setActive(name)} className={`h-14 ${width} rounded-xl border-2 bg-white text-center text-2xl font-black outline-none ${active === name ? "border-cyan-600 ring-4 ring-cyan-100" : "border-indigo-300"}`} />;
  if (activity === "decimal-expansion-example") return <LessonTaskFrame eyebrow="Dział 1 · Klasa 6" heading="Zamiana przez rozszerzanie" description="Jeżeli mianownik można rozszerzyć do 10, 100 lub 1000, otrzymujemy zapis dziesiętny bez dzielenia pisemnego." contentClassName="grid gap-5"><section className="grid gap-5 rounded-2xl border-2 border-amber-300 bg-amber-50 p-6 text-center text-3xl font-black text-slate-950"><div className="flex flex-wrap items-center justify-center gap-4"><FractionView value={{ n: 3, d: 4 }} /><span>=</span><FractionView value={{ n: 75, d: 100 }} /><span>= 0,75</span></div><p className="text-base text-amber-950">Licznik i mianownik rozszerzamy przez 25 — mianownik wynosi wtedy 100.</p></section></LessonTaskFrame>;
  const heading = activity === "decimal-expansion-practice" ? "Rozszerz i zapisz dziesiętnie" : activity === "decimal-long-division" ? "Rozwinięcie dziesiętne przez dzielenie" : "Rozwinięcie skończone i okresowe";
  const description = activity === "decimal-expansion-practice" ? "Rozszerz licznik i mianownik przez tę samą liczbę. Następnie zapisz wynik dziesiętnie." : activity === "decimal-long-division" ? "Gdy nie da się otrzymać mianownika 10, 100 lub 1000, dzielimy licznik przez mianownik pisemnie." : "Rozwinięcie może się skończyć albo powtarzać. Powtarzające się cyfry to okres, który zapisujemy w nawiasie.";
  return <LessonTaskFrame eyebrow="Dział 1 · Klasa 6" heading={heading} description={description} questionNumber={questionNumber} questionCount={questionCount} contentClassName="grid gap-5" data-decimal-expansion={activity}><section className="grid gap-5 rounded-2xl border-2 border-indigo-200 bg-indigo-50 p-6 text-center text-3xl font-black text-slate-950"><div className="flex flex-wrap items-center justify-center gap-4"><FractionView value={task.f} />{activity === "decimal-expansion-practice" ? <><span>=</span><span>rozszerz przez</span>{field("factor", "Mnożnik rozszerzenia", "w-20")}</> : <><span>=</span><span>{task.f.n} : {task.f.d}</span></>}</div>{activity === "decimal-long-division" ? <div className="mx-auto max-w-md rounded-xl bg-white p-4 text-base font-bold text-indigo-950">Przykład: <FractionView value={{ n: 5, d: 9 }} /> = 5 : 9 = 0,(5). Przy dzieleniu kolejne reszty są takie same, więc cyfry będą się powtarzać.</div> : null}<div className="flex flex-wrap items-center justify-center gap-3"><span>=</span>{field("answer", activity === "decimal-expansion-practice" ? "Zapis dziesiętny" : "Rozwinięcie dziesiętne", "w-44")}</div>{activity !== "decimal-expansion-practice" && !readOnly ? <div className="flex justify-center gap-3"><button type="button" onClick={() => periodToken("(")} className="rounded-lg border-2 border-indigo-300 bg-white px-5 py-2 text-xl">(</button><button type="button" onClick={() => periodToken(")")} className="rounded-lg border-2 border-indigo-300 bg-white px-5 py-2 text-xl">)</button></div> : null}{activity === "decimal-period" ? <div className="flex flex-wrap justify-center gap-3"><button type="button" disabled={readOnly} onClick={() => { setType("skończone"); reset(); }} className={`rounded-xl border-2 px-5 py-3 text-lg ${type === "skończone" ? "border-indigo-700 bg-indigo-700 text-white" : "border-indigo-200 bg-white"}`}>skończone</button><button type="button" disabled={readOnly} onClick={() => { setType("okresowe"); reset(); }} className={`rounded-xl border-2 px-5 py-3 text-lg ${type === "okresowe" ? "border-indigo-700 bg-indigo-700 text-white" : "border-indigo-200 bg-white"}`}>okresowe</button></div> : null}</section>{!readOnly ? <LessonNumericKeypad allowSeparator label="Kalkulator do rozwinięć dziesiętnych" helperText={active === "factor" ? "Wpisz mnożnik rozszerzenia." : "Wpisz zapis dziesiętny; okres ujmij w nawias."} onKey={key} onConfirm={confirm} /> : null}{feedback === "good" ? <p role="status" className="rounded-xl bg-emerald-100 p-4 text-center font-black text-emerald-900">✓ Poprawnie.</p> : null}{feedback === "bad" ? <p role="status" className="rounded-xl bg-rose-100 p-4 text-center font-black text-rose-900">Sprawdź rozszerzenie, dzielenie lub zapis okresu w nawiasie.</p> : null}</LessonTaskFrame>;
}
