import { ZooSprintBoard, type ZooBoardTeam } from "@/components/agile/ZooSprintBoard";
import { initializeZooGameAction } from "@/lib/actions/zooGame";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";

export default async function ZooBoardPage({searchParams}:{searchParams:Promise<{sessionId?:string}>}){
  const teacher=await requireRole("teacher");const {sessionId}=await searchParams;const supabase=await createClient();let query=supabase.from("agile_game_sessions").select("id,status").eq("teacher_id",teacher.id).eq("template_id","zoo-sprint").in("status",["lobby","active","finished"]);query=sessionId?query.eq("id",sessionId):query.order("created_at",{ascending:false}).limit(1);const {data:session}=await query.maybeSingle<{id:string;status:string}>();if(!session)return <p className="rounded-2xl bg-amber-50 p-5 font-bold text-amber-900">Najpierw utwórz Zoo Sprint dla klasy w panelu Gier klasowych.</p>;if(session.status!=="finished")await initializeZooGameAction(session.id);
  const [{data:sprints},{data:teams},{data:states},{data:history},{data:stories}]=await Promise.all([supabase.from("agile_zoo_sprints").select("id,sprint_number,status,event_id").eq("session_id",session.id).order("sprint_number",{ascending:false}).limit(1),supabase.from("agile_game_teams").select("id,name,color").eq("session_id",session.id),supabase.from("agile_zoo_team_state").select("team_id,visitors,budget,crises").eq("session_id",session.id),supabase.from("agile_game_team_snapshots").select("team_id,sprint_number,visitors,budget").eq("session_id",session.id).order("sprint_number"),supabase.from("agile_game_story_events").select("team_id,sprint_number,body").eq("session_id",session.id).order("sprint_number")]);const sprint=sprints?.[0];if(!sprint)return <p>Nie udało się utworzyć sprintu.</p>;
  const [{data:choices},{data:previousSprints}]=await Promise.all([supabase.from("agile_zoo_task_choices").select("team_id,task_id").eq("sprint_id",sprint.id),supabase.from("agile_zoo_sprints").select("id").eq("session_id",session.id).neq("id",sprint.id)]);const previousIds=(previousSprints??[]).map(row=>row.id);const {data:usedChoices}=previousIds.length?await supabase.from("agile_zoo_task_choices").select("team_id,task_id").in("sprint_id",previousIds):{data:[]};
  const boardTeams:ZooBoardTeam[]=(teams??[]).map(team=>{const state=(states??[]).find(row=>row.team_id===team.id);return{id:team.id,name:team.name,color:team.color,visitors:Number(state?.visitors??150),budget:Number(state?.budget??50),crises:Array.isArray(state?.crises)?state.crises.map(String):[],selected:(choices??[]).filter(row=>row.team_id===team.id).map(row=>row.task_id),used:(usedChoices??[]).filter(row=>row.team_id===team.id).map(row=>row.task_id),history:(history??[]).filter(point=>point.team_id===team.id).map(point=>({sprint:point.sprint_number,visitors:Number(point.visitors),budget:Number(point.budget)})),story:(stories??[]).filter(event=>event.team_id===team.id).map(event=>({sprint:event.sprint_number,body:event.body}))}});return <main><ZooSprintBoard sprintId={sprint.id} sprintNumber={sprint.sprint_number} status={session.status==="finished"?"finished":sprint.status} eventId={sprint.event_id} teams={boardTeams}/></main>;
}
