/** @vitest-environment jsdom */
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { Grade4StoryProblemsTwoLessonLab } from "@/components/lessons/models/Grade4StoryProblemsTwoLessonLab";

const typeNumber = (value: string) => { for (const digit of value) fireEvent.click(screen.getByRole("button", { name: digit })); };
describe("Grade4StoryProblemsTwoLessonLab", () => {
  afterEach(cleanup);
  it("pokazuje pełne porządkowanie danych na przykładzie akwarium", () => { render(<Grade4StoryProblemsTwoLessonLab activity="information" />); expect(screen.getByText("Kiryski").parentElement).toHaveTextContent("17 + 7 = 24"); expect(screen.getByText("Neony").parentElement).toHaveTextContent("24 + 4 = 28"); expect(screen.getByText("Odpowiedź: W akwarium jest 81 ryb.")).toBeInTheDocument(); });
  it("blokuje klawiaturę urządzenia i używa klawiatury lekcyjnej", () => { render(<Grade4StoryProblemsTwoLessonLab activity="practice" questionNumber={1} questionCount={6} />); for (const input of screen.getAllByRole("textbox")) { expect(input).toHaveAttribute("inputmode", "none"); expect(input).toHaveAttribute("readonly"); } expect(screen.getByLabelText("Klawiatura do uporządkowania danych")).toBeInTheDocument(); });
  it("pokazuje ilustrację gęsi niezależną od obsługi emoji", () => { render(<Grade4StoryProblemsTwoLessonLab activity="practice" questionNumber={3} questionCount={6} />); expect(screen.getByRole("img", { name: "Gęś" })).toBeInTheDocument(); expect(screen.getAllByText("Gęsi")).toHaveLength(2); });
  it("zalicza uporządkowanie kolejki krok po kroku", () => { const onResultChange = vi.fn(); render(<Grade4StoryProblemsTwoLessonLab activity="practice" questionNumber={1} questionCount={6} onResultChange={onResultChange} />); typeNumber("18"); fireEvent.click(screen.getByLabelText("Miejsce Joli")); typeNumber("9"); fireEvent.click(screen.getByLabelText("Wszystkich osób")); typeNumber("35"); fireEvent.click(screen.getByRole("button", { name: "Zatwierdź" })); expect(onResultChange).toHaveBeenLastCalledWith(true, "Miejsce Wojtka: 18, Miejsce Joli: 9, Wszystkich osób: 35"); expect(screen.getByRole("status")).toHaveTextContent("W kolejce stoi 35 osób."); });
  it("nie przyjmuje niepełnego rozwiązania", () => { const onResultChange = vi.fn(); render(<Grade4StoryProblemsTwoLessonLab activity="practice" questionNumber={2} questionCount={6} onResultChange={onResultChange} />); typeNumber("25"); fireEvent.click(screen.getByRole("button", { name: "Zatwierdź" })); expect(screen.getByRole("alert")).toHaveTextContent("Uzupełnij wszystkie wyniki pośrednie i odpowiedź."); expect(onResultChange).not.toHaveBeenCalledWith(expect.any(Boolean), expect.any(String)); });
  it("po błędzie pokazuje wszystkie poprawne wyniki", () => { const onResultChange = vi.fn(); render(<Grade4StoryProblemsTwoLessonLab activity="practice" questionNumber={6} questionCount={6} onResultChange={onResultChange} />); typeNumber("8"); fireEvent.click(screen.getByLabelText("Liczba butelek")); typeNumber("140"); fireEvent.click(screen.getByRole("button", { name: "Zatwierdź" })); expect(onResultChange).toHaveBeenLastCalledWith(false, "Liczba zespołów: 8, Liczba butelek: 140"); expect(screen.getByRole("status")).toHaveTextContent("Poprawne wyniki to: Liczba zespołów — 9, Liczba butelek — 144. Dziś bez punktu."); });
});
