"use client";

import { useState } from "react";
import { LessonNumericKeypad } from "@/components/lessons/models/LessonNumericKeypad";
import { LessonTaskFrame } from "@/components/lessons/LessonTaskFrame";

export type Grade4StoryProblemsTwoActivity = "information" | "practice";
export function grade4StoryProblemsTwoActivityFromStageId(stageId: string): Grade4StoryProblemsTwoActivity { return stageId.endsWith("-information") ? "information" : "practice"; }

type VisualKind = "queue" | "shelves" | "animals" | "route" | "cards" | "teams";
type Field = { label: string; answer: number };
type StoryTask = { visual: VisualKind; prompt: string; fields: Field[]; answer: string; clue: string };

const TASKS: StoryTask[] = [
  { visual: "queue", prompt: "Jola i Wojtek stoją w kolejce po autograf. Między nimi stoi 8 osób. Przed Wojtkiem jest 17 osób, w tym Jola. Za Jolą stanęło 26 osób. Ile osób stoi w kolejce?", fields: [{ label: "Miejsce Wojtka", answer: 18 }, { label: "Miejsce Joli", answer: 9 }, { label: "Wszystkich osób", answer: 35 }], answer: "W kolejce stoi 35 osób.", clue: "Najpierw ustal miejsce Wojtka, potem cofnij się o Jolę i 8 osób stojących między nimi." },
  { visual: "shelves", prompt: "Na środkowej półce jest 18 książek. Na górnej jest o 7 książek więcej niż na środkowej, a na dolnej o 5 mniej niż na górnej. Ile książek jest razem?", fields: [{ label: "Górna półka", answer: 25 }, { label: "Dolna półka", answer: 20 }, { label: "Razem", answer: 63 }], answer: "Na półkach są razem 63 książki.", clue: "Nie obliczaj sumy od razu. Najpierw znajdź liczbę książek na każdej półce." },
  { visual: "animals", prompt: "W zagrodzie są 24 kury. Kaczek jest dwa razy mniej niż kur, a gęsi jest o 5 więcej niż kaczek. Ile ptaków jest w zagrodzie?", fields: [{ label: "Kaczki", answer: 12 }, { label: "Gęsi", answer: 17 }, { label: "Wszystkie ptaki", answer: 53 }], answer: "W zagrodzie są 53 ptaki.", clue: "Najpierw oblicz liczbę kaczek. Dopiero od niej zależy liczba gęsi." },
  { visual: "route", prompt: "Pierwszego dnia turyści przeszli 16 km. Drugiego dnia przeszli o 7 km więcej niż pierwszego, a trzeciego o 5 km mniej niż drugiego. Ile kilometrów przeszli przez trzy dni?", fields: [{ label: "Drugi dzień", answer: 23 }, { label: "Trzeci dzień", answer: 18 }, { label: "Cała trasa", answer: 57 }], answer: "Turyści przeszli 57 km.", clue: "Długość trzeciego odcinka zależy od wyniku z drugiego dnia, nie od pierwszego." },
  { visual: "cards", prompt: "Olek ma 15 kart. Kuba ma trzy razy tyle kart co Olek, a Lena ma o 8 kart mniej niż Kuba. Ile kart mają razem?", fields: [{ label: "Kuba", answer: 45 }, { label: "Lena", answer: 37 }, { label: "Razem", answer: 97 }], answer: "Dzieci mają razem 97 kart.", clue: "Najpierw oblicz liczbę kart Kuby. Od niej zależy liczba kart Leny." },
  { visual: "teams", prompt: "W turnieju bierze udział 72 dzieci. Organizator dzieli je na zespoły po 8 osób. Dla każdego uczestnika przygotowano po 2 butelki wody. Ile powstanie zespołów i ile butelek trzeba przygotować?", fields: [{ label: "Liczba zespołów", answer: 9 }, { label: "Liczba butelek", answer: 144 }], answer: "Powstanie 9 zespołów i potrzeba 144 butelek wody.", clue: "Liczbę zespołów i liczbę butelek oblicza się z tych samych 72 uczestników, ale innymi działaniami." },
];

interface Props { activity: Grade4StoryProblemsTwoActivity; taskSeed?: number; questionNumber?: number; questionCount?: number; readOnly?: boolean; onResultChange?: (correct: boolean | null, answer?: string) => void }

function InformationSlide() {
  return <LessonTaskFrame eyebrow="Dział 1 · Temat 12" heading="Najpierw uporządkuj wszystkie dane" description="W trudniejszym zadaniu jeden wynik często staje się daną potrzebną do następnego kroku.">
    <div className="space-y-5">
      <p className="rounded-3xl bg-amber-50 p-5 text-center text-xl font-black leading-relaxed text-amber-950 ring-2 ring-amber-200">W akwarium są 4 rodzaje ryb. Gupików jest 17, molinezji 12, kirysków jest o 7 więcej niż gupików i o 4 mniej niż neonów. Ile ryb jest w akwarium?</p>
      <section className="rounded-3xl bg-cyan-50 p-5 ring-2 ring-cyan-200"><p className="mb-4 text-center text-sm font-black uppercase tracking-[.16em] text-cyan-900">Uporządkuj dane — każda ryba w osobnej karcie</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Gupiki", "17"], ["Molinezje", "12"], ["Kiryski", "17 + 7 = 24"], ["Neony", "24 + 4 = 28"]].map(([name, value]) => <div key={name} className="rounded-2xl bg-white p-4 text-center shadow ring-2 ring-violet-200"><p className="text-3xl" aria-hidden>🐟</p><p className="font-black text-violet-900">{name}</p><p className="mt-2 text-xl font-black text-slate-950">{value}</p></div>)}</div></section>
      <section className="grid gap-3 sm:grid-cols-3">{[["1. Pierwsza zależność", "Kirysków: 17 + 7 = 24"], ["2. Druga zależność", "Neonów: 24 + 4 = 28"], ["3. Dopiero teraz suma", "17 + 12 + 24 + 28 = 81"]].map(([title, body]) => <div key={title} className="rounded-2xl bg-slate-100 p-4 text-center"><p className="font-black text-slate-950">{title}</p><p className="mt-2 font-bold text-slate-700">{body}</p></div>)}</section>
      <div className="rounded-2xl bg-emerald-100 p-4 text-center text-xl font-black text-emerald-950">Odpowiedź: W akwarium jest 81 ryb.</div>
      <p className="rounded-2xl bg-violet-100 p-4 text-center font-black text-violet-950">Nie dodawaj liczb od razu. Najpierw wypisz wszystkie szukane wielkości i zaznacz, od której informacji zależą.</p>
    </div>
  </LessonTaskFrame>;
}

function TaskVisual({ kind }: { kind: VisualKind }) {
  if (kind === "queue") return <div className="flex flex-wrap items-center justify-center gap-2 text-center"><span className="rounded-xl bg-slate-200 px-3 py-2 font-black">8 osób przed Jolą</span><span className="rounded-full bg-rose-200 px-4 py-3 font-black">Jola</span><span className="rounded-xl bg-amber-200 px-3 py-2 font-black">8 osób między nimi</span><span className="rounded-full bg-blue-200 px-4 py-3 font-black">Wojtek</span><span className="rounded-xl bg-slate-200 px-3 py-2 font-black">pozostałe osoby</span></div>;
  if (kind === "shelves") return <div className="mx-auto max-w-md space-y-3">{[["Górna", "?"], ["Środkowa", "18"], ["Dolna", "?"]].map(([name, count]) => <div key={name} className="flex items-center justify-between rounded-xl border-b-8 border-amber-700 bg-amber-50 px-5 py-3"><span className="font-black">{name}</span><span className="text-2xl font-black text-violet-800">{count} 📚</span></div>)}</div>;
  if (kind === "animals") return <div className="grid grid-cols-3 gap-3 text-center">{[["Kury", "24", "🐔"], ["Kaczki", "2 razy mniej", "🦆"], ["Gęsi", "o 5 więcej", "🪿"]].map(([name, relation, icon]) => <div key={name} className="rounded-2xl bg-white p-3 shadow ring-2 ring-emerald-200"><p className="text-4xl" aria-hidden>{icon}</p><p className="font-black">{name}</p><p className="mt-1 font-bold text-emerald-800">{relation}</p></div>)}</div>;
  if (kind === "route") return <div className="grid grid-cols-3 gap-3 text-center">{[["Dzień 1", "16 km"], ["Dzień 2", "+ 7 km"], ["Dzień 3", "− 5 km od dnia 2"]].map(([day, distance]) => <div key={day} className="rounded-2xl bg-emerald-100 p-4 ring-2 ring-emerald-300"><p className="font-black text-emerald-950">{day}</p><p className="mt-2 font-black">{distance}</p></div>)}</div>;
  if (kind === "cards") return <div className="flex flex-wrap justify-center gap-3 text-center">{[["Olek", "15"], ["Kuba", "3 razy tyle"], ["Lena", "o 8 mniej od Kuby"]].map(([name, relation]) => <div key={name} className="rounded-2xl bg-violet-100 p-4 ring-2 ring-violet-300"><p className="text-3xl" aria-hidden>🃏</p><p className="font-black text-violet-950">{name}</p><p className="mt-1 font-bold">{relation}</p></div>)}</div>;
  return <div className="flex flex-wrap items-center justify-center gap-4 text-center"><div className="rounded-2xl bg-cyan-100 p-5 ring-2 ring-cyan-300"><p className="text-3xl font-black">72</p><p className="font-black">uczestników</p></div><div className="rounded-2xl bg-amber-100 p-5 ring-2 ring-amber-300"><p className="text-3xl font-black">8</p><p className="font-black">osób w zespole</p></div><div className="rounded-2xl bg-blue-100 p-5 ring-2 ring-blue-300"><p className="text-3xl font-black">2</p><p className="font-black">butelki na osobę</p></div></div>;
}

function PracticeSlide({ task, questionNumber, questionCount, readOnly, onResultChange }: { task: StoryTask; questionNumber: number; questionCount: number; readOnly: boolean; onResultChange?: Props["onResultChange"] }) {
  const [values, setValues] = useState(() => task.fields.map(() => ""));
  const [activeField, setActiveField] = useState(0);
  const [feedback, setFeedback] = useState<"correct" | "incorrect" | "missing" | null>(null);
  const locked = readOnly || feedback === "correct" || feedback === "incorrect";
  const edit = (key: string) => { if (locked) return; setValues((current) => current.map((value, index) => index !== activeField ? value : key === "backspace" ? value.slice(0, -1) : value.length >= 3 ? value : `${value}${key}`)); setFeedback(null); onResultChange?.(null); };
  const check = () => { if (values.some((value) => value === "")) { setFeedback("missing"); return; } const correct = values.every((value, index) => Number(value) === task.fields[index]?.answer); setFeedback(correct ? "correct" : "incorrect"); onResultChange?.(correct, values.map((value, index) => `${task.fields[index]?.label}: ${value}`).join(", ")); };
  return <LessonTaskFrame eyebrow="Dział 1 · Temat 12" heading="Uporządkuj dane i rozwiąż" description="Uzupełnij wyniki pośrednie. Dopiero ostatnia kratka odpowiada na pytanie z zadania." questionNumber={questionNumber} questionCount={questionCount}>
    <div className="space-y-4"><section className="rounded-3xl bg-cyan-50 p-5 ring-2 ring-cyan-200"><TaskVisual kind={task.visual} /></section><p className="rounded-3xl bg-amber-50 p-5 text-center text-xl font-black leading-relaxed text-amber-950 ring-2 ring-amber-200">{task.prompt}</p><section className="rounded-3xl bg-violet-50 p-5 ring-2 ring-violet-200"><p className="mb-4 text-center text-sm font-black uppercase tracking-[.16em] text-violet-800">Miejsce na uporządkowanie danych</p><div className={`grid gap-3 ${task.fields.length === 2 ? "sm:grid-cols-2" : "sm:grid-cols-3"}`}>{task.fields.map((field, index) => <label key={field.label} className={`rounded-2xl bg-white p-3 text-center shadow ring-2 ${activeField === index && !locked ? "ring-violet-600" : "ring-violet-200"}`}><span className="block min-h-10 font-black text-slate-700">{field.label}</span><input aria-label={field.label} value={values[index]} inputMode="none" readOnly onClick={() => !locked && setActiveField(index)} className="mt-2 h-14 w-full rounded-xl border-2 border-violet-300 bg-white text-center text-2xl font-black text-slate-950 outline-none" /></label>)}</div></section><p className="rounded-2xl bg-slate-100 p-3 text-center font-bold text-slate-700"><span className="font-black text-slate-950">Jak zacząć:</span> {task.clue}</p>{!readOnly ? <LessonNumericKeypad onKey={edit} onConfirm={check} disabled={locked} label="Klawiatura do uporządkowania danych" helperText="Dotknij wybranej kratki i wpisz kolejne wyniki." /> : null}{feedback === "missing" ? <p role="alert" className="rounded-2xl bg-amber-100 p-3 text-center font-black text-amber-950">Uzupełnij wszystkie wyniki pośrednie i odpowiedź.</p> : null}{feedback === "correct" ? <div role="status" className="rounded-2xl bg-emerald-100 p-3 text-center font-black text-emerald-950"><p>Brawo! Dane są uporządkowane poprawnie.</p><p className="mt-1">{task.answer}</p></div> : null}{feedback === "incorrect" ? <div role="status" className="rounded-2xl bg-amber-100 p-3 text-center font-black text-amber-950"><p>Spróbuj innym razem. Poprawne wyniki to: {task.fields.map((field) => `${field.label} — ${field.answer}`).join(", ")}. Dziś bez punktu.</p><p className="mt-1">{task.answer}</p></div> : null}</div>
  </LessonTaskFrame>;
}

export function Grade4StoryProblemsTwoLessonLab({ activity, taskSeed = 0, questionNumber = 1, questionCount = TASKS.length, readOnly = false, onResultChange }: Props) { if (activity === "information") return <InformationSlide />; const task = TASKS[Math.max(0, (questionNumber - 1) % TASKS.length)] ?? TASKS[Math.abs(taskSeed) % TASKS.length]!; return <PracticeSlide key={`${questionNumber}-${task.prompt}`} task={task} questionNumber={questionNumber} questionCount={questionCount} readOnly={readOnly} onResultChange={onResultChange} />; }
